#!/usr/bin/env node
'use strict';

const process = require('process');
const config  = require('./lib/config');
const blocks  = require('./lib/blocks');
const clients = require('./lib/clients');


class Bar {
  constructor() {
    this.blocks = [
      new blocks.StaticBlock(`%{U${config.get('cUnderline')}}`),
      new blocks.StaticBlock('%{l}'),
      new blocks.I3ModeBlock(),
      new blocks.WorkspaceBlock(),
      new blocks.StaticBlock('%{c}'),
      new blocks.DatetimeBlock(),
      new blocks.StaticBlock('%{r}'),
      new blocks.WeatherBlock('San Diego, CA', 'C'),
      new blocks.SsidBlock(),
      new blocks.PlayStatusBlock(),
      new blocks.VolumeBlock(),
      new blocks.BatteryBlock(),
    ];

    // Re-render on every update
    this.blocks.forEach((block) => {
      block.on('update', this.render.bind(this));
    });

    // Prevous render
    this.prev = '';

    this.render();
  }

  // Update all blocks
  update() {
    this.blocks.forEach((block) => {
      block.update();
    });
  }

  // Print the output of all blocks concatenated
  render() {
    let cur = this.blocks.map((block) => {
      return block.query();
    }).join('');

    if (cur !== this.prev) {
      this.prev = cur;
      console.log(cur);
    }
  }
}

// Do configuration from command line options
let argv = require('minimist')(process.argv.slice(2), {
  alias: {
    B: 'cBG',
    A: 'cAccent',
    U: 'cUrgent',
    L: 'cUnderline'
  }
});
delete argv._;
config.update(argv);

let bar = new Bar();

// Update all blocks on lid open
clients.acpi.on('button/lid', function(_, state) {
  if (state === 'open')
    setTimeout(bar.update.bind(bar), config.get('lidOpenTimeout'));
});

// vim: ft=javascript

